# Uncomment this line to define a global platform for your project
platform :ios, '14.0.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'GoogleUtilities'
  use_frameworks! :linkage => :static
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '11.13.0'
end

# Allow building with static transitive dependencies when using dynamic frameworks
# This is a common workaround when `use_frameworks!` is required but some pods
# statically link binaries (like Flutter itself).
# See: https://github.com/CocoaPods/CocoaPods/issues/9420

pre_install do |installer|
  # workaround for https://github.com/superlistapp/super_native_extensions/issues/21
  installer.pod_targets.each do |pod|
    if pod.name.eql?('super_native_extensions')
      def pod.build_type;
        Pod::BuildType.dynamic_framework
      end
    end
  end
  # This fixes the Transitive Dependencies statically linked error
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        # dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        # dart: PermissionGroup.photos
        'PERMISSION_PHOTOS=1',

        # dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

         # dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        'PERMISSION_LOCATION=1',
      ]
    end
  end
end

target 'ImageNotification' do
  use_frameworks! :linkage => :static
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities'
end
